app = "soundingboard"

[build]
  dockerfile = "Dockerfile"

[env]
  PORT = "3000"

[[services]]
  internal_port = 3000
  protocol = "tcp"

  [[services.ports]]
    port = 80
    handlers = ["http"]
    force_https = true

  [[services.ports]]
    port = 443
    handlers = ["tls"]

  [[services.concurrency]]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.http_checks]]
    path = "/"
    method = "GET"
    interval = "30s"
    timeout = "10s"
    grace_period = "60s"
    protocol = "http"
